# app/core/errors/error_codes.py

from enum import Enum


class ErrorCode(str, Enum):

    # 用户相关
    MISSING_USER_IDENTIFIER = "MISSING_USER_IDENTIFIER"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # 用户画像相关 / Task 相关
    MISSING_LAST_TASK = "MISSING_LAST_TASK"
    TASK_NOT_FOUND_IN_REPO = "TASK_NOT_FOUND_IN_REPO"
    MISSING_WEEKLY_MISSED_TASKS = "MISSING_WEEKLY_MISSED_TASKS"
    INVALID_LATEST_LEVEL1_SCORES = "INVALID_LATEST_LEVEL1_SCORES"
    NEW_USER_PLAN_NOT_AVAILABLE = "NEW_USER_PLAN_NOT_AVAILABLE"

    TRAINING_TASK_NOT_AVAILABLE = "TRAINING_TASK_NOT_AVAILABLE"

    # 数据相关
    DATA_FILE_NOT_FOUND = "DATA_FILE_NOT_FOUND"
    COLUMN_MAPPING_NOT_FOUND = "COLUMN_MAPPING_NOT_FOUND"

    # Task
    TASK_REPO_EMPTY = "TASK_REPO_EMPTY"
    TASK_REPO_BUILD_FAILED = "TASK_REPO_BUILD_FAILED"

    # 模型
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
    SCORE_PREDICTION_FAILED = "SCORE_PREDICTION_FAILED"

    # LLM
    LLM_CALL_FAILED = "LLM_CALL_FAILED"

    # AI 推荐
    AI_PLAN_GENERATION_FAILED = "AI_PLAN_GENERATION_FAILED"

    # 通用
    INTERNAL_ERROR = "INTERNAL_ERROR"
