llm:
  type: api   # local 或 api

  local:
    model_path: /data/models/qwen2
    base_url: http://localhost:8000

  api:
    base_url: http://localhost:8000
    api_key: sk-xxxxx
    model: qwen2_vl


score_prediction:
  type: lightgbm   # 预测模型类型：lightgbm / xgboost / mlp / least_square

  lightgbm:
    checkpoints:
      perception: checkpoints/cognitive_l1/perception_lightgbm.txt
      attention: checkpoints/cognitive_l1/attention_lightgbm.txt
      memory: checkpoints/cognitive_l1/memory_lightgbm.txt
      executive_function: checkpoints/cognitive_l1/executive_function_lightgbm.txt


runtime:
  timeout: 60
  max_retries: 3

csv_to_parquet:

  interval_seconds: 300

  files:

    - csv: data/external/raw/alg_cogtrain_brainscore_task_child.csv
      parquet: data/external/raw/alg_cogtrain_brainscore_task_child.parquet

    - csv: data/external/raw/alg_training_task_child.csv
      parquet: data/external/raw/alg_training_task_child.parquet